name: Maven Build and Trivy Scan

on:
  push:
    branches:
      - main

jobs:
  ####################################################
  # Job 1: Compile
  ####################################################
  compile:
    runs-on: Mac-OS-Runner

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Install Maven
        run: |
          brew update
          brew install maven

      - name: Compile Maven Project
        run: mvn clean compile

      - name: Resolve Maven Dependencies
        run: mvn dependency:resolve

  ####################################################
  # Job 2: Build
  ####################################################
  build:
    runs-on: Mac-OS-Runner
    needs: compile

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build Maven Project
        run: mvn clean package

      - name: Install Trivy
        run: |
          brew update
          brew install trivy

      - name: Trivy File System Scan
        run: |
          trivy fs --format table .

      - name: Install Gitleaks
        run: |
          brew update
          brew install gitleaks

      - name: Run Gitleaks Scan
        run: gitleaks detect --source . --verbose

  ####################################################
  # Job 3: Test
  ####################################################
  test:
    runs-on: Mac-OS-Runner
    needs: build

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Unit Test cases
        run: mvn test