name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:

##################################################
# JOB 1 : BUILD
##################################################

  compile:
    runs-on: ubuntu-latest

    steps:

      # Step 1
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3
      - name: Compile Project
        run: mvn compile

      # Step 4
      - name: Download Maven Dependencies
        run: mvn dependency:resolve

      # Step 5
      - name: Upload Maven Repository
        uses: actions/upload-artifact@v4
        with:
          name: maven-cache
          path: ~/.m2

##################################################
# JOB 2 : SECURITY SCAN
##################################################

  security-check:

    needs: compile

    runs-on: ubuntu-latest

    steps:
      # Step 1
      - name: Checkout Source Code
        uses: actions/checkout@v4

      # Step 2
      - name: Download Maven Repository
        uses: actions/download-artifact@v4
        with:
          name: maven-cache
          path: ~/.m2

      # Step 3
      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg

          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | \
          gpg --dearmor | sudo tee /usr/share/keyrings/trivy.gpg > /dev/null

          echo "deb [signed-by=/usr/share/keyrings/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main" | \
          sudo tee /etc/apt/sources.list.d/trivy.list

          sudo apt-get update
          sudo apt-get install -y trivy

      # Step 4
      - name: Trivy File System Scan
        run: |
          trivy fs --format json -o trivy-report.json .

      # Step 5
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2
